config/routes.rb
Rails.application.routes.draw do

  root 'dogs#index'

  resources :dogs, only: [:index, :show]

  namespace :api do
    namespace :v1 do
      resources :dogs, only: :index
    end
  end

end

app/models/dog.rb
require 'open-uri'

class Dog < ActiveRecord::Base
  validates_presence_of :name

  scope :rising_stars, -> { where created_at: 1.year.ago..Time.now }

  def older_than? other
    updated_at < other.updated_at
  end

  def related_photo
    tags = name.split(' ').join(',')
    api_url = "https://api.flickr.com/services/feeds/photos_public.gne?tags=#{tags}"
    doc = Nokogiri::XML(open(api_url))

    doc.at('entry').at('link').attributes['href'].value
  end
end

app/controllers/api/v1/dogs_controller.rb
class Api::V1::DogsController < ApplicationController
  def index
    render json: Dog.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
  end

  def show
    @dog = Dog.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dogs/index.html.erb
<%- @dogs.each do |dog| %>
  <%= link_to dog.name, dog_path(dog) %>
<%- end %>

app/views/dogs/show.html.erb
<%= image_tag @dog.image, id: 'profile_pic' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TddWithRor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>